In [2]:
#Esercizio Dal database AdventureWorks estraiamo la tabella dimproduct 
    #• Sulla colonna DealerPrice, utilizzando il metodo .round(), arrotondiamo i valori alle due cifre decimali, e poi al valore intero più vicino 
    #• Utilizzando il metodo .clip(), facciamo in modo che i valori siano compresi tra un minimo di 0 e un massimo di 1000

import os
import pandas as pd
import pymysql
import dotenv

dotenv.load_dotenv(dotenv_path=".env", override=True)
username = os.getenv("username")
password = os.getenv("password")
hostname = os.getenv("hostname")
database = os.getenv("database")

connection = pymysql.connect(
    host=hostname,
    user=username,
    password=password,
    database=database,
    cursorclass=pymysql.cursors.DictCursor,
)

query = "SELECT * FROM dimproduct;"
cursor = connection.cursor()
cursor.execute(query)
result = cursor.fetchall()

cursor.close()
connection.close()

df = pd.DataFrame(result)

In [37]:
df = df.drop_duplicates()
df['DealerPrice'].info
df['DealerPrice'] = df['DealerPrice'].fillna(0)
df['DealerPrice'].info
print('--- Sulla colonna DealerPrice, utilizzando il metodo .round(), arrotondiamo i valori alle due cifre decimali, e poi al valore intero più vicino ---')
print(df['DealerPrice'].round(2))
df['DealerPrice'] = df['DealerPrice'].round(0)
print("\n",df['DealerPrice'])

print('--- Utilizzando il metodo .clip(), facciamo in modo che i valori siano compresi tra un minimo di 0 e un massimo di 1000 ---')
df['DealerPrice'] = df['DealerPrice'].clip(lower=0, upper=1000)
print("\n",df['DealerPrice'])
print(df[['ProductKey', 'EnglishProductName', 'DealerPrice']].head(10))
print(df[['ProductKey', 'EnglishProductName', 'DealerPrice']].tail(10))

--- Sulla colonna DealerPrice, utilizzando il metodo .round(), arrotondiamo i valori alle due cifre decimali, e poi al valore intero più vicino ---
0        0.0
1        0.0
2        0.0
3        0.0
4        0.0
       ...
601     61.0
602     73.0
603    324.0
604    324.0
605    324.0
Name: DealerPrice, Length: 606, dtype: float64

 0        0.0
1        0.0
2        0.0
3        0.0
4        0.0
       ...
601     61.0
602     73.0
603    324.0
604    324.0
605    324.0
Name: DealerPrice, Length: 606, dtype: float64
--- Utilizzando il metodo .clip(), facciamo in modo che i valori siano compresi tra un minimo di 0 e un massimo di 1000 ---

 0        0.0
1        0.0
2        0.0
3        0.0
4        0.0
       ...
601     61.0
602     73.0
603    324.0
604    324.0
605    324.0
Name: DealerPrice, Length: 606, dtype: float64
   ProductKey     EnglishProductName  DealerPrice
0           1        Adjustable Race          0.0
1           2           Bearing Ball          0.0
2           3        BB Ball Bearing          0.0
3           4  Headset Ball Bearings          0.0
4           5                  Blade          0.0
5           6            LL Crankarm          0.0
6           7            ML Crankarm          0.0
7           8            HL Crankarm          0.0
8           9        Chainring Bolts          0.0
9          10          Chainring Nut          0.0
     ProductKey      EnglishProductName  DealerPrice
596         597  Mountain-500 Black, 42        324.0
597         598  Mountain-500 Black, 44        324.0
598         599  Mountain-500 Black, 48        324.0
599         600  Mountain-500 Black, 52        324.0
600         601       LL Bottom Bracket         32.0
601         602       ML Bottom Bracket         61.0
602         603       HL Bottom Bracket         73.0
603         604      Road-750 Black, 44        324.0
604         605      Road-750 Black, 48        324.0
605         606      Road-750 Black, 52        324.0

In [53]:
#Esercizio Creiamo un DataFrame sintetico, che contiene i guadagni mensili di diverse annate, con il seguente codice:
import numpy as np
years = 5 
guadagni = pd.DataFrame({"Mese": list("GFMAMGLASOND"*years),
                         "Anno": np.repeat(list(range(years)), 12),
                         "Valore": np.random.randint(800, 5000, 12*years)}) 
    #• Calcola la somma cumulativa dei guadagni utilizzando il metodo .cumsum() 
    #• Come sopra, ma raggruppato per ogni anno usando prima un .groupby()

g = guadagni
print("La somma cumulativa totale sul valore è:\n",g["Valore"].cumsum())

print("La somma cumulativa per anno sul valore è:\n",g.groupby('Anno')['Valore'].cumsum())

La somma cumulativa totale sul valore è:
 0       4863
1       7608
2       9366
3      12462
4      14788
5      16413
6      19918
7      24046
8      25996
9      28894
10     32410
11     36623
12     39155
13     44033
14     48509
15     50683
16     53129
17     54372
18     56452
19     60750
20     65376
21     67338
22     69405
23     71734
24     75501
25     80487
26     82561
27     86866
28     90382
29     92849
30     96719
31     99941
32    102745
33    104598
34    107753
35    108805
36    111306
37    113429
38    115589
39    119675
40    121895
41    126244
42    128834
43    132916
44    133851
45    138014
46    140008
47    143730
48    146159
49    149467
50    150576
51    153537
52    156424
53    159936
54    163755
55    164920
56    169735
57    173830
58    174815
59    176028
Name: Valore, dtype: int64
La somma cumulativa per anno sul valore è:
 0      4863
1      7608
2      9366
3     12462
4     14788
5     16413
6     19918
7     24046
8     25996
9     28894
10    32410
11    36623
12     2532
13     7410
14    11886
15    14060
16    16506
17    17749
18    19829
19    24127
20    28753
21    30715
22    32782
23    35111
24     3767
25     8753
26    10827
27    15132
28    18648
29    21115
30    24985
31    28207
32    31011
33    32864
34    36019
35    37071
36     2501
37     4624
38     6784
39    10870
40    13090
41    17439
42    20029
43    24111
44    25046
45    29209
46    31203
47    34925
48     2429
49     5737
50     6846
51     9807
52    12694
53    16206
54    20025
55    21190
56    26005
57    30100
58    31085
59    32298
Name: Valore, dtype: int32

In [54]:
#Esercizio 1/2 Dal database AdventureWorks estraiamo la tabella dimcustomer 
    #• Trasformiamo i nomi dei clienti in modo che abbiano solo lettere minuscole, e i cognomi in modo che abbiano solo lettere maiuscole 
    #• Sulla colonna EmailAddress, utilizzando il metodo .str.split(), estraiamo nome utente e dominio 
    #• Sulla colonna Phone, estraiamo ogni parte del numero (ad es. da "1 (11) 500 555-0162" a ["1", "(11)", "500", "555-0162"]) 
    #• Utilizzando il metodo .str.contains(), estraiamo tutti gli indirizzi e-mail che contengono il numero "21"
connection = pymysql.connect(
    host=hostname,
    user=username,
    password=password,
    database=database,
    cursorclass=pymysql.cursors.DictCursor,
)

query_customer = "SELECT * FROM dimcustomer;"
cursor = connection.cursor()
cursor.execute(query_customer)
result_customer = cursor.fetchall()

cursor.close()
connection.close()

df_customer = pd.DataFrame(result_customer)

In [56]:
#• Trasformiamo i nomi dei clienti in modo che abbiano solo lettere minuscole, e i cognomi in modo che abbiano solo lettere maiuscole 
df_customer['FirstName'] = df_customer['FirstName'].str.lower()
df_customer['LastName'] = df_customer['LastName'].str.upper()

#• Sulla colonna EmailAddress, utilizzando il metodo .str.split(), estraiamo nome utente e dominio 
df_customer[['Username', 'Domain']] = df_customer['EmailAddress'].str.split('@', expand=True)

#• Sulla colonna Phone, estraiamo ogni parte del numero (ad es. da "1 (11) 500 555-0162" a ["1", "(11)", "500", "555-0162"]) 
df_customer['Phone_Parts'] = df_customer['Phone'].str.split(' ')

#• Utilizzando il metodo .str.contains(), estraiamo tutti gli indirizzi e-mail che contengono il numero "21"
emails_21 = df_customer[df_customer['EmailAddress'].str.contains("21", na=False)]

# Verify the results
print(df_customer[['FirstName', 'LastName', 'EmailAddress', 'Username', 'Domain', 'Phone_Parts']].head())

   FirstName LastName                    EmailAddress    Username  \
0        jon     YANG       jon24@adventure-works.com       jon24
1     eugene    HUANG    eugene10@adventure-works.com    eugene10
2      ruben   TORRES     ruben35@adventure-works.com     ruben35
3    christy      ZHU   christy12@adventure-works.com   christy12
4  elizabeth  JOHNSON  elizabeth5@adventure-works.com  elizabeth5

                Domain               Phone_Parts
0  adventure-works.com  [1, (11), 500, 555-0162]
1  adventure-works.com  [1, (11), 500, 555-0110]
2  adventure-works.com  [1, (11), 500, 555-0184]
3  adventure-works.com  [1, (11), 500, 555-0162]
4  adventure-works.com  [1, (11), 500, 555-0131]

In [58]:
#Esercizio 2/2 
    #• Estraiamo tutti gli indirizzi e-mail che contengono il numero "20" oppure il numero "10" 
    #• Calcolare la lunghezza di ogni indirizzo e-mail ed estrarre i cinque più lunghi e i cinque più corti 
    #• Modificare il dominio degli indirizzi e-mail da "adventure-works.com" a "aw-db.com" mediante il metodo .str.replace() 
    #• Dalla colonna AddressLine1 estraiamo tutti gli indirizzi che contengono la sottostringa "Street"

#• Estraiamo tutti gli indirizzi e-mail che contengono il numero "20" oppure il numero "10"  
emails_10_20 = df_customer[df_customer['EmailAddress'].str.contains("20|10", na=False)]

#• Calcolare la lunghezza di ogni indirizzo e-mail ed estrarre i cinque più lunghi e i cinque più corti
df_customer['Email_Length'] = df_customer['EmailAddress'].str.len()
longest_5_emails = df_customer.nlargest(5, 'Email_Length')
shortest_5_emails = df_customer.nsmallest(5, 'Email_Length')

#• Modificare il dominio degli indirizzi e-mail da "adventure-works.com" a "aw-db.com" mediante il metodo .str.replace() 
df_customer['EmailAddress'] = df_customer['EmailAddress'].str.replace('adventure-works.com', 'aw-db.com', regex=False)

#• Dalla colonna AddressLine1 estraiamo tutti gli indirizzi che contengono la sottostringa "Street"
street_addresses = df_customer[df_customer['AddressLine1'].str.contains("Street", na=False)]


print(emails_10_20[['EmailAddress']].head())
print(longest_5_emails[['EmailAddress', 'Email_Length']])
print(shortest_5_emails[['EmailAddress', 'Email_Length']])
print(street_addresses[['AddressLine1']].head())

             EmailAddress
1      eugene10@aw-db.com
10  jacquelyn20@aw-db.com
22      ethan20@aw-db.com
30    bethany10@aw-db.com
32     denise10@aw-db.com
                 EmailAddress  Email_Length
979   christopher25@aw-db.com            23
1767  christopher18@aw-db.com            23
2655  christopher23@aw-db.com            23
3512  christopher27@aw-db.com            23
4772  christopher10@aw-db.com            23
         EmailAddress  Email_Length
3974     k0@aw-db.com            12
15299    y0@aw-db.com            12
8      rob4@aw-db.com            14
53     ana0@aw-db.com            14
215    ana7@aw-db.com            14
           AddressLine1
7      942 Brook Street
12    4785 Scott Street
32   626 Bentley Street
63   4927 Virgil Street
125  8481 Zartop Street

In [70]:
#Esercizio 1/2 Dai beginner_datasets carichiamo in un DataFrame il file facebook.csv, che contiene dei post con data di pubblicazione, tipo (foto, video, …) #e numero di reactions raccolte: 
    #• Con la funzione pd.to_datetime() convertiamo la colonna status_published in formato Timestamp 
    #• Utilizzando gli attributi .dt.year , .dt.month , .dt.day , .dt.dayofweek , .dt.dayofyear, ottieniamo informazioni specifiche sulle date delle transazioni, come l'anno, il mese, il giorno della settimana, il giorno dell'anno, eccetera
path_fb = "C:/Users/Alessandro Personale/Desktop/Dataset/Dataset/beginner_datasets/facebook.csv"
df_f = pd.read_csv(path_fb)
df_f

#• Con la funzione pd.to_datetime() convertiamo la colonna status_published in formato Timestamp
df_f['status_published'] = pd.to_datetime(df_f['status_published'])

#• Utilizzando gli attributi .dt.year , .dt.month , .dt.day , .dt.dayofweek , .dt.dayofyear, ottieniamo informazioni specifiche sulle date delle transazioni, come l'anno, il mese, il giorno della settimana, il giorno dell'anno, eccetera
df_f['Year'] = df_f['status_published'].dt.year
df_f['Month'] = df_f['status_published'].dt.month
df_f['Day'] = df_f['status_published'].dt.day
df_f['DayOfWeek'] = df_f['status_published'].dt.dayofweek
df_f['DayOfYear'] = df_f['status_published'].dt.dayofyear

risultato = ['status_published', 'Year', 'Month', 'Day', 'DayOfWeek', 'DayOfYear']
print(df_f[risultato].head())

#Esercizio 2/2 
    #• Estraiamo solo i post relativi al 2012 
    #• Estraiamo solo i post relativi a maggio 2018 
    #• Confrontiamo il numero di post pubblicati nei weekend rispetto al numero di post pubblicati nel resto della settimana 
    #• Troviamo il primo e ultimo post pubblicati in ogni anno 
    #• Quanti tipi di post ci sono? E quanti per ogni tipo?

#• Estraiamo solo i post relativi al 2012
posts_2012 = df_f[df_f['Year'] == 2012]

#• Estraiamo solo i post relativi a maggio 2018 
posts_may_2018 = df_f[(df_f['Year'] == 2018) & (df_f['Month'] == 5)]

#• Confrontiamo il numero di post pubblicati nei weekend rispetto al numero di post pubblicati nel resto della settimana 
df_f['Weekend'] = df_f['DayOfWeek'].isin([5, 6])
weekend_counts = df_f['Weekend'].value_counts()

#• Troviamo il primo e ultimo post pubblicati in ogni anno 
primo_ultimo_post = df_f.groupby('Year')['status_published'].agg(['min', 'max'])

#• Quanti tipi di post ci sono? E quanti per ogni tipo?
unique_types_count = df_f['status_type'].nunique()
posts_per_type = df_f['status_type'].value_counts()

print(f"--- Numeri di post nel 2012: {len(posts_2012)} ---")
print(f"--- Numeri di post a Maggio 2018: {len(posts_may_2018)} ---")

print("\n--- Weekdays vs Weekends ---")
print(weekend_counts)

print("\n--- Primo e ultimo Post per anno ---")
print(primo_ultimo_post)

print(f"\n--- il totale di post unici: {unique_types_count} ---")
print(posts_per_type)

     status_published  Year  Month  Day  DayOfWeek  DayOfYear
0 2018-04-22 06:00:00  2018      4   22          6        112
1 2018-04-21 22:45:00  2018      4   21          5        111
2 2018-04-21 06:17:00  2018      4   21          5        111
3 2018-04-21 02:29:00  2018      4   21          5        111
4 2018-04-18 03:22:00  2018      4   18          2        108
--- Numeri di post nel 2012: 589 ---
--- Numeri di post a Maggio 2018: 595 ---

--- Weekdays vs Weekends ---
Weekend
False    5009
True     2041
Name: count, dtype: int64

--- Primo e ultimo Post per anno ---
                     min                 max
Year
2012 2012-07-15 02:51:00 2012-12-23 03:11:00
2013 2013-01-02 02:23:00 2013-12-31 23:38:00
2014 2014-01-05 09:23:00 2014-12-10 07:42:00
2015 2015-01-02 03:41:00 2015-12-31 08:20:00
2016 2016-01-03 04:23:00 2016-12-31 05:13:00
2017 2017-01-02 08:25:00 2017-12-31 22:15:00
2018 2018-01-01 01:39:00 2018-06-13 01:12:00

--- il totale di post unici: 4 ---
status_type
photo     4288
video     2334
status     365
link        63
Name: count, dtype: int64

In [81]:
#Esercizio Dai beginner_dataset carichiamo in un DataFrame il file pokemon.csv: 
    #• Tramite i metodi .isnull() e .sum() controlliamo se ci sono valori nulli nel dataset e contiamo quanti valori nulli ci sono in ogni colonna 
    #• Ci sono valori nulli? 
    #• Se sì, avrebbe senso cercare di riempirli? 
    #• Eliminiamo le righe che contengono valori nulli
path_pokemon = "C:/Users/Alessandro Personale/Desktop/Dataset/Dataset/beginner_datasets/pokemon.csv"
df_p = pd.read_csv(path_pokemon)
df_p

#• Tramite i metodi .isnull() e .sum() controlliamo se ci sono valori nulli nel dataset e contiamo quanti valori nulli ci sono in ogni colonna
df_p.isnull().sum()
df_p["Type 2"]

#• Ci sono valori nulli?
print("I valori nulli sono",df_p["Type 2"].isnull().sum())

#• Se sì, avrebbe senso cercare di riempirli?
#no

#• Eliminiamo le righe che contengono valori nulli
df_p.dropna(inplace=True)
print("\n--- Verifica dopo aver eliminato i valori nulli ---")
print(df_p.isnull().sum())
print(f"\nNumero di Pokémon rimasti nel dataset (con doppio tipo): {len(df_p)}")

I valori nulli sono 386

--- Verifica dopo aver eliminato i valori nulli ---
#             0
Name          0
Type 1        0
Type 2        0
Total         0
HP            0
Attack        0
Defense       0
Sp. Atk       0
Sp. Def       0
Speed         0
Generation    0
Legendary     0
dtype: int64

Numero di Pokémon rimasti nel dataset (con doppio tipo): 414

In [107]:
#Esercizio Dai beginner_dataset carichiamo in un DataFrame il file automobile.csv: 
    #• Ci sono valori nulli? Dove? Quanti? 
    #• Quali righe hanno un valore nullo nella colonna num-of-doors? 
    #• Esaminando i dati nel dataset, cerchiamo una logica per sostituire i valori nulli nella colonna num-of-doors

path_automobile = "C:/Users/Alessandro Personale/Desktop/Dataset/Dataset/beginner_datasets/automobile.csv"
df_aut = pd.read_csv(path_automobile)
df_aut

#• Ci sono valori nulli? Dove? Quanti?
df_aut.isnull().sum() #normalized-losses, num-of-doors

#• Quali righe hanno un valore nullo nella colonna num-of-doors?
null_doors_rows = df_aut[df_aut['num-of-doors'].isnull()]
print("righe hanno un valore nullo nella colonna num-of-doors")
display(null_doors_rows)

#• Esaminando i dati nel dataset, cerchiamo una logica per sostituire i valori nulli nella colonna num-of-doors
df_aut.sample(50)
df_raggruppato = df_aut.groupby('body-style')['num-of-doors']
sedan_doors = df_raggruppato.get_group('sedan')
print(sedan_doors)
sedan_doors.describe() #top four

df_aut['num-of-doors'] = df_aut['num-of-doors'].fillna('four')
valori_nulli_rimasti = df_aut['num-of-doors'].isnull().sum()
print(f"Valori nulli rimasti in 'num-of-doors': {valori_nulli_rimasti}")

righe hanno un valore nullo nella colonna num-of-doors

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
26,1,148.0,dodge,gas,turbo,NaN,sedan,fwd,front,93.7,...,98,mpfi,3.03,3.39,7.6,102,5500,24,30,8558
60,0,NaN,mazda,diesel,std,NaN,sedan,fwd,front,98.8,...,122,idi,3.39,3.39,22.7,64,4650,36,42,10795

3      four
4      four
5       two
6      four
8      four
       ...
197    four
198    four
199    four
200    four
201    four
Name: num-of-doors, Length: 95, dtype: object
Valori nulli rimasti in 'num-of-doors': 0

In [112]:
#Esercizio Abbiamo il seguente DataFrame che raccoglie le misurazioni di un sensore che misura la temperatura atmosferica giornaliera: 
import numpy as np, pandas as pd 
temp = pd.DataFrame({"Giorno": [0, 1, 2, 3, 4, 5, 6, 
                                7, 8, 9, 10, 11, 12], 
                     "Temperature": [18, 19, 18, np.nan, 21, 20, 20,
                                     np.nan, 21, 23, np.nan, 23, 24]})
    #• Il sensore a volte non funziona, dunque alcuni dati sono mancanti: quale sarebbe la migliore strategia per gestirli?
display(temp)
temp['Temperature_Clean'] = temp['Temperature'].interpolate()
display(temp)

    Giorno  Temperature
0        0         18.0
1        1         19.0
2        2         18.0
3        3          NaN
4        4         21.0
5        5         20.0
6        6         20.0
7        7          NaN
8        8         21.0
9        9         23.0
10      10          NaN
11      11         23.0
12      12         24.0

    Giorno  Temperature  Temperature_Clean
0        0         18.0               18.0
1        1         19.0               19.0
2        2         18.0               18.0
3        3          NaN               19.5
4        4         21.0               21.0
5        5         20.0               20.0
6        6         20.0               20.0
7        7          NaN               20.5
8        8         21.0               21.0
9        9         23.0               23.0
10      10          NaN               23.0
11      11         23.0               23.0
12      12         24.0               24.0

In [115]:
#Esercizio 1/2 Nel pacchetto os della standard library c'è la funzione os.listdir() che permette di avere la lista dei nomi di file all'interno di una directory; 
#senza input di default li cerca nella directory di lavoro corrente, altrimenti si può passare un path per esaminare una directory specifica, 
#ad esempio os.listdir("mio_progetto/beginner_datasets/") 
    #• Nella directory dei beginner_datasets, quali sono i dataset che contengono dati nulli?
    #• Dovremo usare un ciclo for per esaminare tutti i nomi dei file 2. 3. 4. 5. 6. 
    #• Dovremo selezionare solo i nomi di file con estensione .csv (quindi usare un costrutto if) 
    #• Nel corpo dovremo leggere di volta in volta il file in esame, e caricarlo in un DataFrame con la funzione .read_csv() 
    #• Sul DataFrame dovremo utilizzare il metodo .isna() per trovare la maschera booleana dei dati nulli 
    #• Dovremo contare i dati nulli, utilizzando .sum(); potremmo doverlo utilizzare più di una volta 
    #• Dovremo stampare, o memorizzare in una list, solo i nomi dei file che contengono dati nulli
path = "C:/Users/Alessandro Personale/Desktop/Dataset/Dataset/beginner_datasets/"

csv_list = os.listdir(path)

datasets_val_nulli = []

print("--- Analisi dei valori nulli nei dataset (beginner_dataset) ---\n")

for csv in csv_list:
    if csv.endswith('.csv'):
        full_path = os.path.join(path, csv)
        
        try:
            df_total = pd.read_csv(full_path)
            total_nulls = df_total.isna().sum().sum()
            
            if total_nulls > 0:
                datasets_val_nulli.append(csv)
                print(f"[X] {csv} contiene {total_nulls} valori nulli.")
            else:
                print(f"[V] {csv} non ha valori nulli.")       
                
        except Exception as e:
            print(f"[!] Non posso leggere {csv}: {e}")
        
print("\n--- Fine ---")
print("Datasets con valori nulli:", datasets_val_nulli)

--- Analisi dei valori nulli nei dataset (beginner_dataset) ---

[V] amazon.csv non ha valori nulli.
[V] anomaly.csv non ha valori nulli.
[V] asia_gdp.csv non ha valori nulli.
[X] automobile.csv contiene 39 valori nulli.
[V] bank.csv non ha valori nulli.
[V] bike.csv non ha valori nulli.
[V] blood.csv non ha valori nulli.
[V] boston.csv non ha valori nulli.
[V] cancer.csv non ha valori nulli.
[V] concrete.csv non ha valori nulli.
[V] credit.csv non ha valori nulli.
[V] diabetes.csv non ha valori nulli.
[V] diamond.csv non ha valori nulli.
[X] elections.csv contiene 52 valori nulli.
[V] electrical_grid.csv non ha valori nulli.
[V] employee.csv non ha valori nulli.
[V] energy.csv non ha valori nulli.
[V] facebook.csv non ha valori nulli.
[V] forest.csv non ha valori nulli.
[X] france.csv contiene 66 valori nulli.
[V] germany.csv non ha valori nulli.
[V] glass.csv non ha valori nulli.
[V] gold.csv non ha valori nulli.
[V] heart.csv non ha valori nulli.
[V] heart_disease.csv non ha valori nulli.
[X] hepatitis.csv contiene 153 valori nulli.
[X] house.csv contiene 7829 valori nulli.
[X] income.csv contiene 4262 valori nulli.
[V] insurance.csv non ha valori nulli.
[V] ipl.csv non ha valori nulli.
[V] iris.csv non ha valori nulli.
[V] jewellery.csv non ha valori nulli.
[V] juice.csv non ha valori nulli.
[V] kiva.csv non ha valori nulli.
[X] mice.csv contiene 1396 valori nulli.
[V] migration.csv non ha valori nulli.
[X] nba.csv contiene 11 valori nulli.
[V] parkinsons.csv non ha valori nulli.
[X] pokemon.csv contiene 386 valori nulli.
[V] poker.csv non ha valori nulli.
[X] population.csv contiene 12 valori nulli.
[V] public_health.csv non ha valori nulli.
[V] questions.csv non ha valori nulli.
[V] satellite.csv non ha valori nulli.
[X] seeds.csv contiene 4 valori nulli.
[V] spx.csv non ha valori nulli.
[X] traffic.csv contiene 48143 valori nulli.
[V] tweets.csv non ha valori nulli.
[V] wholesale.csv non ha valori nulli.
[X] wikipedia.csv contiene 68 valori nulli.
[V] wine.csv non ha valori nulli.

--- Fine ---
Datasets con valori nulli: ['automobile.csv', 'elections.csv', 'france.csv', 'hepatitis.csv', 'house.csv', 'income.csv', 'mice.csv', 'nba.csv', 'pokemon.csv', 'population.csv', 'seeds.csv', 'traffic.csv', 'wikipedia.csv']