In [1]:
#Esercizio 1/3 Estraiamo la tabella dimproduct dal database AdventureWorks, e valutiamo quanto segue: 
    #• Quanti dati ci sono in totale? 
    #• Quali sono i metadati? 
    #• Stampiamo il primo elemento
    #• Stampiamo l'ultimo elemento 
    #• Riusciamo a stampare cinque elementi a caso? 
    #• Quali sono i colori disponibili?
!pip install pymysql

import os
import pandas as pd
import pymysql
import dotenv

dotenv.load_dotenv(dotenv_path=".env", override=True)
username = os.getenv("username")
password = os.getenv("password")
hostname = os.getenv("hostname")
database = os.getenv("database")

connection = pymysql.connect(
    host=hostname,
    user=username,
    password=password,
    database=database,
    cursorclass=pymysql.cursors.DictCursor,
)

query = "SELECT * FROM dimproduct;"
cursor = connection.cursor()
cursor.execute(query)
result = cursor.fetchall()

df = pd.DataFrame(result)
display(df)

print('---')
print('---Quanti dati ci sono in totale?---')
print(f"Il dataset contiene {len(df)} record,  {df.shape[0]} righe e {df.shape[1]} colonne")

print('---')
print('---Quali sono i metadati?---')
print(df.info())

print('---')
print('---Stampiamo il primo elemento---')
print(df.iloc[0])
display(df.head(1))

print('---')
print('---Stampiamo l\'ultimo elemento---')
print(df.iloc[-1])
display(df.tail(1))

print('---')
print('---Riusciamo a stampare cinque elementi a caso?---')
print(df.sample(5))
display(df.sample(5))

print('---')
print('---Quali sono i colori disponibili?---')
colori = df['Color'].dropna().unique()
colori_unici = colori[1:]
print("I colori unici sono:")
for colore in colori_unici:
    print(colore)

#connection.close()

Requirement already satisfied: pymysql in c:\users\ssi106\appdata\local\anaconda3\lib\site-packages (1.1.3)

,ProductKey,ProductAlternateKey,ProductSubcategoryKey,WeightUnitMeasureCode,SizeUnitMeasureCode,EnglishProductName,SpanishProductName,FrenchProductName,StandardCost,FinishedGoodsFlag,...,ChineseDescription,ArabicDescription,HebrewDescription,ThaiDescription,GermanDescription,JapaneseDescription,TurkishDescription,StartDate,EndDate,Status
0,1,AR-5381,NaN,None,None,Adjustable Race,,,None,0,...,None,None,None,None,None,None,None,2003-07-01,NaT,Current
1,2,BA-8327,NaN,None,None,Bearing Ball,,,None,0,...,None,None,None,None,None,None,None,2003-07-01,NaT,Current
2,3,BE-2349,NaN,None,None,BB Ball Bearing,,,None,0,...,None,None,None,None,None,None,None,2003-07-01,NaT,Current
3,4,BE-2908,NaN,None,None,Headset Ball Bearings,,,None,0,...,None,None,None,None,None,None,None,2003-07-01,NaT,Current
4,5,BL-2036,NaN,None,None,Blade,,,None,0,...,None,None,None,None,None,None,None,2003-07-01,NaT,Current
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
601,602,BB-8107,5.0,G,None,ML Bottom Bracket,Eje de pedalier GM,Axe de pédalier ML,44.9500,1,...,铝合金车圈；大直径脚蹬轴。,فناجين من سبيكة الألومنيوم؛ ذات محور دوران كبي...,כיסויים מסגסוגת אלומיניום; ציר רחב-קוטר.,ดุมอลูมิเนียมอัลลอยด์ แกนเพลาขนาดใหญ่,Außenringe aus Aluminiumlegierung; Radachse mi...,アルミニウム合金カップ、大径スピンドル。,Alüminyum alaşımı orta göbekler; geniş çaplı mil.,2013-07-01,NaT,Current
602,603,BB-9108,5.0,G,None,HL Bottom Bracket,Eje de pedalier GA,Axe de pédalier HL,53.9400,1,...,铝合金车圈和空心轴。,فناجين من سبيكة الألومنيوم ومحور أجوف.,כיסויים מסגסוגת אלומיניום וציר חלול.,ดุมอลูมิเนียมอัลลอยด์และเพลากลวง,Außenringe aus Aluminiumlegierung und hohle Ac...,アルミニウム合金カップとホロー アクスル。,Alüminyum alaşımı orta göbekler ve içi boş aks.,2013-07-01,NaT,Current
603,604,BK-R19B-44,2.0,LB,CM,"Road-750 Black, 44","Carretera: 750, negra, 44","Vélo de route 750 noir, 44",343.6500,1,...,入门级成人自行车；确保越野旅行或公路骑乘的舒适。快拆式车毂和轮缘。,إنها دراجة مناسبة للمبتدئين من البالغين؛ فهي ت...,"אופני מבוגרים למתחילים; מציעים רכיבה נוחה ""מחו...",จักรยานระดับเริ่มต้นสำหรับผู้ใหญ่ ให้ความสบายใ...,Ein Erwachsenenrad für Einsteiger; bietet Komf...,エントリー レベルに対応する、クロスカントリーにも街への買い物にも快適な、大人の自転車。ハブ...,"""Başlangıç seviyesinde yetişkin bisikleti, kır...",2013-07-01,NaT,Current
604,605,BK-R19B-48,2.0,LB,CM,"Road-750 Black, 48","Carretera: 750, negra, 48","Vélo de route 750 noir, 48",343.6500,1,...,入门级成人自行车；确保越野旅行或公路骑乘的舒适。快拆式车毂和轮缘。,إنها دراجة مناسبة للمبتدئين من البالغين؛ فهي ت...,"אופני מבוגרים למתחילים; מציעים רכיבה נוחה ""מחו...",จักรยานระดับเริ่มต้นสำหรับผู้ใหญ่ ให้ความสบายใ...,Ein Erwachsenenrad für Einsteiger; bietet Komf...,エントリー レベルに対応する、クロスカントリーにも街への買い物にも快適な、大人の自転車。ハブ...,"""Başlangıç seviyesinde yetişkin bisikleti, kır...",2013-07-01,NaT,Current
605,606,BK-R19B-52,2.0,LB,CM,"Road-750 Black, 52","Carretera: 750, negra, 52","Vélo de route 750 noir, 52",343.6500,1,...,入门级成人自行车；确保越野旅行或公路骑乘的舒适。快拆式车毂和轮缘。,إنها دراجة مناسبة للمبتدئين من البالغين؛ فهي ت...,"אופני מבוגרים למתחילים; מציעים רכיבה נוחה ""מחו...",จักรยานระดับเริ่มต้นสำหรับผู้ใหญ่ ให้ความสบายใ...,Ein Erwachsenenrad für Einsteiger; bietet Komf...,エントリー レベルに対応する、クロスカントリーにも街への買い物にも快適な、大人の自転車。ハブ...,"""Başlangıç seviyesinde yetişkin bisikleti, kır...",2013-07-01,NaT,Current

---
---Quanti dati ci sono in totale?---
Il dataset contiene 606 record,  606 righe e 36 colonne
---
---Quali sono i metadati?---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 606 entries, 0 to 605
Data columns (total 36 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   ProductKey             606 non-null    int64
 1   ProductAlternateKey    606 non-null    object
 2   ProductSubcategoryKey  397 non-null    float64
 3   WeightUnitMeasureCode  282 non-null    object
 4   SizeUnitMeasureCode    253 non-null    object
 5   EnglishProductName     606 non-null    object
 6   SpanishProductName     606 non-null    object
 7   FrenchProductName      606 non-null    object
 8   StandardCost           397 non-null    object
 9   FinishedGoodsFlag      606 non-null    int64
 10  Color                  606 non-null    object
 11  SafetyStockLevel       606 non-null    int64
 12  ReorderPoint           606 non-null    int64
 13  ListPrice              395 non-null    object
 14  Size                   299 non-null    object
 15  SizeRange              606 non-null    object
 16  Weight                 282 non-null    float64
 17  DaysToManufacture      606 non-null    int64
 18  ProductLine            380 non-null    object
 19  DealerPrice            395 non-null    object
 20  Class                  330 non-null    object
 21  Style                  301 non-null    object
 22  ModelName              397 non-null    object
 23  LargePhoto             606 non-null    object
 24  EnglishDescription     396 non-null    object
 25  FrenchDescription      396 non-null    object
 26  ChineseDescription     396 non-null    object
 27  ArabicDescription      396 non-null    object
 28  HebrewDescription      396 non-null    object
 29  ThaiDescription        396 non-null    object
 30  GermanDescription      396 non-null    object
 31  JapaneseDescription    396 non-null    object
 32  TurkishDescription     396 non-null    object
 33  StartDate              606 non-null    datetime64[ns]
 34  EndDate                200 non-null    datetime64[ns]
 35  Status                 406 non-null    object
dtypes: datetime64[ns](2), float64(2), int64(5), object(27)
memory usage: 170.6+ KB
None
---
---Stampiamo il primo elemento---
ProductKey                                                               1
ProductAlternateKey                                                AR-5381
ProductSubcategoryKey                                                  NaN
WeightUnitMeasureCode                                                 None
SizeUnitMeasureCode                                                   None
EnglishProductName                                         Adjustable Race
SpanishProductName
FrenchProductName
StandardCost                                                          None
FinishedGoodsFlag                                                        0
Color                                                                   NA
SafetyStockLevel                                                      1000
ReorderPoint                                                           750
ListPrice                                                             None
Size                                                                  None
SizeRange                                                               NA
Weight                                                                 NaN
DaysToManufacture                                                        0
ProductLine                                                           None
DealerPrice                                                           None
Class                                                                 None
Style                                                                 None
ModelName                                                             None
LargePhoto               b'GIF89a\xf0\x00\x95\x00\xf7\x00\x00\x00\x00\x...
EnglishDescription                                                    None
FrenchDescription                                                     None
ChineseDescription                                                    None
ArabicDescription                                                     None
HebrewDescription                                                     None
ThaiDescription                                                       None
GermanDescription                                                     None
JapaneseDescription                                                   None
TurkishDescription                                                    None
StartDate                                              2003-07-01 00:00:00
EndDate                                                                NaT
Status                                                             Current
Name: 0, dtype: object

,ProductKey,ProductAlternateKey,ProductSubcategoryKey,WeightUnitMeasureCode,SizeUnitMeasureCode,EnglishProductName,SpanishProductName,FrenchProductName,StandardCost,FinishedGoodsFlag,...,ChineseDescription,ArabicDescription,HebrewDescription,ThaiDescription,GermanDescription,JapaneseDescription,TurkishDescription,StartDate,EndDate,Status
0,1,AR-5381,NaN,None,None,Adjustable Race,,,None,0,...,None,None,None,None,None,None,None,2003-07-01,NaT,Current

---
---Stampiamo l'ultimo elemento---
ProductKey                                                             606
ProductAlternateKey                                             BK-R19B-52
ProductSubcategoryKey                                                  2.0
WeightUnitMeasureCode                                                   LB
SizeUnitMeasureCode                                                     CM
EnglishProductName                                      Road-750 Black, 52
SpanishProductName                               Carretera: 750, negra, 52
FrenchProductName                               Vélo de route 750 noir, 52
StandardCost                                                      343.6500
FinishedGoodsFlag                                                        1
Color                                                                Black
SafetyStockLevel                                                       100
ReorderPoint                                                            75
ListPrice                                                         539.9900
Size                                                                    52
SizeRange                                                         48-52 CM
Weight                                                               20.42
DaysToManufacture                                                        4
ProductLine                                                              R
DealerPrice                                                       323.9940
Class                                                                    L
Style                                                                    U
ModelName                                                         Road-750
LargePhoto               b'GIF89a\xf0\x00\x95\x00\xf7\x00\x00\x8avw\xf7...
EnglishDescription       Entry level adult bike; offers a comfortable r...
FrenchDescription        Vélo d'adulte d'entrée de gamme ; permet une c...
ChineseDescription                       入门级成人自行车；确保越野旅行或公路骑乘的舒适。快拆式车毂和轮缘。
ArabicDescription        إنها دراجة مناسبة للمبتدئين من البالغين؛ فهي ت...
HebrewDescription        אופני מבוגרים למתחילים; מציעים רכיבה נוחה "מחו...
ThaiDescription          จักรยานระดับเริ่มต้นสำหรับผู้ใหญ่ ให้ความสบายใ...
GermanDescription        Ein Erwachsenenrad für Einsteiger; bietet Komf...
JapaneseDescription      エントリー レベルに対応する、クロスカントリーにも街への買い物にも快適な、大人の自転車。ハブ...
TurkishDescription       "Başlangıç seviyesinde yetişkin bisikleti, kır...
StartDate                                              2013-07-01 00:00:00
EndDate                                                                NaT
Status                                                             Current
Name: 605, dtype: object

,ProductKey,ProductAlternateKey,ProductSubcategoryKey,WeightUnitMeasureCode,SizeUnitMeasureCode,EnglishProductName,SpanishProductName,FrenchProductName,StandardCost,FinishedGoodsFlag,...,ChineseDescription,ArabicDescription,HebrewDescription,ThaiDescription,GermanDescription,JapaneseDescription,TurkishDescription,StartDate,EndDate,Status
605,606,BK-R19B-52,2.0,LB,CM,"Road-750 Black, 52","Carretera: 750, negra, 52","Vélo de route 750 noir, 52",343.6500,1,...,入门级成人自行车；确保越野旅行或公路骑乘的舒适。快拆式车毂和轮缘。,إنها دراجة مناسبة للمبتدئين من البالغين؛ فهي ت...,"אופני מבוגרים למתחילים; מציעים רכיבה נוחה ""מחו...",จักรยานระดับเริ่มต้นสำหรับผู้ใหญ่ ให้ความสบายใ...,Ein Erwachsenenrad für Einsteiger; bietet Komf...,エントリー レベルに対応する、クロスカントリーにも街への買い物にも快適な、大人の自転車。ハブ...,"""Başlangıç seviyesinde yetişkin bisikleti, kır...",2013-07-01,NaT,Current

---
---Riusciamo a stampare cinque elementi a caso?---
     ProductKey ProductAlternateKey  ProductSubcategoryKey  \
264         265          FR-R38R-48                   14.0
180         181             RM-M692                    NaN
393         394             HS-0296                   11.0
97           98             LI-6000                    NaN
424         425             RW-T905                   17.0

    WeightUnitMeasureCode SizeUnitMeasureCode       EnglishProductName  \
264                    LB                  CM  LL Road Frame - Red, 48
180                     G                None          ML Mountain Rim
393                  None                None               LL Headset
97                   None                None   Internal Lock Washer 1
424                  None                None       Touring Rear Wheel

                   SpanishProductName                      FrenchProductName  \
264  Cuadro de carretera GB: rojo, 48  Cadre de vélo de route LL - rouge, 48
180
393                      Dirección GB                    Jeu de direction LL
97
424            Rueda de paseo trasera      Roue arrière de vélo de randonnée

    StandardCost  FinishedGoodsFlag  ...  \
264     187.1600                  1  ...
180         None                  0  ...
393      15.1800                  1  ...
97          None                  0  ...
424     108.7800                  1  ...

                       ChineseDescription  \
264  LL 车架提供了安全舒适的骑乘，经济实惠的铝制车架提供了卓越的避震功能。
180                                  None
393                 无螺纹的车头碗组不仅确保质量而且经济实惠。
97                                   None
424                出色的符合空气动力学的轮缘设计确保平稳骑乘。

                                     ArabicDescription  \
264  يوفر الهيكل LL Frame قيادة آمنة ومريحة، مع توف...
180                                               None
393  توفر الوصلة غير الملولبة بين الشوكة الماسكة لل...
97                                                None
424  إطاران معدنيان ممتازان يتميزان بخاصية الدينامي...

                                     HebrewDescription  \
264  מסגרת ה- LL מספקת רכיבה בטוחה ונוחה ועם זאת, מ...
180                                               None
393         טבעת נטולת תבריג מספקת איכות במחיר חסכוני.
97                                                None
424  חישוקים אווירודינמיים מצוינים מבטיחים רכיבה חלקה.

                                       ThaiDescription  \
264  เฟรม LL ให้ความปลอดภัยและสบายขณะขับขี่ พร้อมทั...
180                                               None
393  ชุดประกอบส่วนหัวไม่มีเกลียว คุณภาพสูงในราคาประ...
97                                                None
424         ขอบล้อแอโรไดนามิคสำหรับการขับขี่ที่นุ่มนวล

                                     GermanDescription  \
264  Mit dem LL-Rahmen fahren Sie sicher und komfor...
180                                               None
393        Hochwertiger Lenkkopf zu einem guten Preis.
97                                                None
424  Hochwertige aerodynamische Felgen für ein komf...

                                   JapaneseDescription  \
264  LL フレームは、安全で快適に乗ることができ、値打ち価格のアルミニウム フレームで優れた衝撃...
180                                               None
393                   スレッドレスのヘッドセットは、手ごろな価格で高品質を提供します。
97                                                None
424                          空気力学的に優れ、滑らかな乗り心地を保証するリム。

                                    TurkishDescription  StartDate    EndDate  \
264  "LL Kadro güvenli ve konforlu sürüş sunar, değ... 2012-07-01 2008-12-27
180                                               None 2003-07-01        NaT
393    Furş takımı kaliteyi ekonomik bir fiyata sunar. 2012-07-01 2008-12-27
97                                                None 2003-07-01        NaT
424  Mükemmel aerodinamik jantlar rahat bir sürüşü ... 2012-07-01 2008-12-27

      Status
264     None
180  Current
393     None
97   Current
424     None

[5 rows x 36 columns]

,ProductKey,ProductAlternateKey,ProductSubcategoryKey,WeightUnitMeasureCode,SizeUnitMeasureCode,EnglishProductName,SpanishProductName,FrenchProductName,StandardCost,FinishedGoodsFlag,...,ChineseDescription,ArabicDescription,HebrewDescription,ThaiDescription,GermanDescription,JapaneseDescription,TurkishDescription,StartDate,EndDate,Status
445,446,PA-T100,35.0,None,None,"Touring-Panniers, Large","Cesta de paseo, grande","Sacoches de vélo de randonnée, grande capacité",51.5600,1,...,易于拿取的耐用防水型尼龙结构。容量尽可满足周末旅行所需。,تركيبة نيلون شديدة التحمل مضادة للماء يمكن الو...,מבנה ניילון יציב ועמיד למים עם גישה קלה. גדול ...,ทนทาน ทำจากไนลอนกันน้ำ ใช้งานง่าย มีขนาดใหญ่พ...,"""Robustes, wasserfestes Nylon und einfacher Zu...",耐久性と防水性に優れた使いやすいナイロン製。週末旅行に最適です。,"""Kolay erişilebilen sağlam, su geçirmez naylon...",2012-07-01,2008-12-27,None
584,585,BK-T18U-44,3.0,LB,CM,"Touring-3000 Blue, 44","Paseo: 3000, azul, 44","Vélo de randonnée 3000 bleu, 44",461.4400,1,...,全能经济型自行车，具备基本的舒适和安全特征。提供了更宽也更稳固的轮胎，适用于环城游或周末旅行。,إنها دراجة قيّمة تصلح لكافة المناسبات وهي تشتم...,אופני איכות לכל מטרה עם תכונות הנוחות והבטיחות...,จักรยานอเนกประสงค์สุดคุ้ม พร้อมความสบายและความ...,"""Ein günstiges Allzweckfahrrad mit Basiskomfor...",ベーシックな快適性と安全性を備えた、多目的で手軽な自転車。街中での走行および週末の小旅行用に...,Temel konfor ve güvenlik özellikleriyle her ye...,2013-07-01,NaT,Current
434,435,FR-R72Y-48,14.0,LB,CM,"ML Road Frame-W - Yellow, 48","Cuadro de carretera para mujer GM: amarillo, 48","Cadre de route ML -W - jaune, 48",300.1200,1,...,ML 车架使用与我们的高档 HL 车架完全相同的铝合金，它的特征是轻型下管经过磨制达到最佳口...,يحتوي هيكل ML على أنبوبة سفلية خفيف الوزن تم ت...,"מסגרת ה- ML, העשויה סגסוגת אלומיניום זהה לזו ה...",สร้างจากอลูมิเนียมอัลลอยชนิดเดียวกับสุดยอดเฟรม...,Der ML-Rahmen ist aus der gleichen Aluminiumle...,当社の最高級 HL フレームと同じアルミニウム合金で作られた ML は、完璧なダウンチューブ...,"""HL kadroyla aynı alüminyum alaşımından imal e...",2012-07-01,2008-12-27,None
117,118,LN-1032,NaN,None,None,Lock Nut 6,,,None,0,...,None,None,None,None,None,None,None,2003-07-01,NaT,Current
478,479,BC-R205,28.0,None,None,Road Bottle Cage,Portabotellas de carretera,Porte-bidon de vélo de route,3.3600,1,...,铝制外胎比山地车胎更轻盈；是长途旅行的完美伴侣。,هيكل قفصي من الألومنيوم أخف من مثيله في طرازنا...,כלוב האלומיניום קל יותר מאשר הגירסה ההררית שלנ...,โครงอลูมิเนียมมีน้ำหนักเบากว่ารุ่นภูเขา เหมาะส...,Aluminiumrahmen ist leichter als unsere Mounta...,アルミニウム ケージは、当社のマウンテン バージョンより軽量で、ツーリングに最適です。,Alüminyum kafes dağ modelimizdekinden daha haf...,2013-07-01,NaT,Current

---
---Quali sono i colori disponibili?---
I colori unici sono:
Black
Silver
Red
White
Blue
Multi
Yellow
Grey
Silver/Black

In [2]:
#Esercizio 2/3 
    #• In media quanto pesano i prodotti (per questo esercizio, ignoriamo l'unità di misura, ma usiamo solo i valori della colonna relativa)? 
    #• Quanto pesa il più leggero? 
    #• Quanto pesa il più pesante? 
    #• Quanti prodotti pesano più di 100? 
    #• Quanto costano in media i prodotti (colonna DealerPrice)? 
    #• Quali sono i quartili dei prezzi?
'''
#Pensavo non fosse nel df ma in altra tables...
dotenv.load_dotenv(dotenv_path=".env", override=True)
username = os.getenv("username")
password = os.getenv("password")
hostname = os.getenv("hostname")
database = os.getenv("database")

connection = pymysql.connect(
    host=hostname,
    user=username,
    password=password,
    database=database,
    cursorclass=pymysql.cursors.DictCursor,
)
tables_query = "SHOW TABLES;"
cursor = connection.cursor()
cursor.execute(tables_query)
result2 = cursor.fetchall()
tables = pd.DataFrame(result2)
display(tables)
'''
pd.set_option('display.max_columns', None)
#display(df)
print("--- Controllo valori nulli ---")
print(df['Weight'].isnull().sum())
serie_peso_pulita = df['Weight'].dropna()

print("--- Diagnostica colonna Weight ---")
# Quanti zeri ci sono?
zeri = (serie_peso_pulita == 0).sum()
print(f"Prodotti che pesano esattamente 0: {zeri}")
# Ci sono pesi negativi?
negativi = (serie_peso_pulita < 0).sum()
print(f"Prodotti con peso negativo: {negativi}")

media_peso_prodotti = serie_peso_pulita.mean()
print("--- In media quanto pesano i prodotti (per questo esercizio, ignoriamo l'unità di misura, ma usiamo solo i valori della colonna relativa)? ---")
print(f"I prodotti hanno un peso medio di:{media_peso_prodotti.round(2)}")

print("--- Quanto pesa il più leggero? ---")
print(f"Il più pesante pesa: {serie_peso_pulita.min()}")

print("--- Quanto pesa il più pesante? ---")
print(f"Il più pesante pesa: {serie_peso_pulita.max()}")

print("--- Quanti prodotti pesano più di 100? ---")
filtro_peso = (serie_peso_pulita > 100).sum()
print(f"I prodotti che pesano più di 100 sono: {filtro_peso}")

print("--- Quanto costano in media i prodotti (colonna DealerPrice)? ---")
print("--- Controllo valori nulli ---")
print(df['DealerPrice'].isnull().sum())
serie_DealerPrice_pulita = df['DealerPrice'].dropna()

print("--- Diagnostica colonna DealerPrice ---")
# Quanti zeri ci sono?
zeri = (serie_DealerPrice_pulita == 0).sum()
print(zeri)
# Ci sono DealerPrice negativi?
negativi = (serie_DealerPrice_pulita < 0).sum()
print(negativi)

print(f"I prodotti costano in media: {serie_DealerPrice_pulita.mean().round(2)} euro")
print("--- Quali sono i quartili dei prezzi? ---")
serie_DealerPrice_pulita2 = serie_DealerPrice_pulita.astype(float)
quartili_prezzo = serie_DealerPrice_pulita2.quantile([0.25, 0.50, 0.75])
print(quartili_prezzo)
#connection.close()

--- Controllo valori nulli ---
324
--- Diagnostica colonna Weight ---
Prodotti che pesano esattamente 0: 0
Prodotti con peso negativo: 0
--- In media quanto pesano i prodotti (per questo esercizio, ignoriamo l'unità di misura, ma usiamo solo i valori della colonna relativa)? ---
I prodotti hanno un peso medio di:56.19
--- Quanto pesa il più leggero? ---
Il più pesante pesa: 2.12
--- Quanto pesa il più pesante? ---
Il più pesante pesa: 1050.0
--- Quanti prodotti pesano più di 100? ---
I prodotti che pesano più di 100 sono: 28
--- Quanto costano in media i prodotti (colonna DealerPrice)? ---
--- Controllo valori nulli ---
211
--- Diagnostica colonna DealerPrice ---
0
0
I prodotti costano in media: 448.6 euro
--- Quali sono i quartili dei prezzi? ---
0.25     41.9940
0.50    218.4540
0.75    722.5949
Name: DealerPrice, dtype: float64

In [3]:
#Esercizio 3/3 
    #• Qual è il prezzo medio per i prodotti di colore blu? 
    #• Qual è il prezzo medio per i prodotti di colore rosso o nero? 
    #• Qual è il prezzo massimo per i prodotti di taglia 42 e peso oltre i 10 Kg? 
    #• Qual è il nome inglese e il costo di produzione (StandardCost) di tutti i prodotti di taglia 42, peso oltre i 10 Kg e colore argento? 
    #• Visualizziamo lo StandardCost e il DealerPrice degli ultimi 20 elementi del dataset: quali sono le differenze? C'è un pattern? C'è qualche elemento che non lo segue?

print('---')
print('--- Qual è il prezzo medio per i prodotti di colore blu? ---')
df_blue = df[df['Color'] == 'Blue']
media_prezzo_blue = df_blue['DealerPrice'].mean().round(2)
print(f"La media dei prezzi dei prodotti blue è: {media_prezzo_blue}")

print('---')
print('--- Qual è il prezzo medio per i prodotti di colore rosso o nero?  ---')
df_nero_rosso = df[df['Color'].isin(['Black','Red'])]
media_prezzo_nero_rosso = df_nero_rosso['DealerPrice'].mean().round(2)
print(f"La media dei prezzi dei prodotti rosi e neri è: {media_prezzo_nero_rosso}")

print('---')
print('--- Qual è il prezzo massimo per i prodotti di taglia 42 e peso oltre i 10 Kg?  ---')
#display(df['Size'])
df_taglia42magg10kg = df[(df['Size'].astype(str) == '42') & (df['Weight'] > 10)]
prezzo_massimo = df_taglia42magg10kg['DealerPrice'].max()
print(f"Prezzo massimo (Taglia 42, Peso > 10): {prezzo_massimo:.2f}")

print('---')
print('--- Qual è il nome inglese e il costo di produzione (StandardCost) di tutti i prodotti di taglia 42, peso oltre i 10 Kg e colore argento?  ---')
size = df['Size'].astype(str) == '42'
peso = df['Weight'] > 10
colore = df['Color'] == 'Silver'
prodotti_silver = df.loc[size & peso & colore, ['EnglishProductName', 'StandardCost']]
print(prodotti_silver)

print('---')
print("--- Visualizziamo lo StandardCost e il DealerPrice degli ultimi 20 elementi del dataset: quali sono le differenze? C'è un pattern? C'è qualche elemento che non lo segue?  ---")
ultimi_20 = df[['StandardCost', 'DealerPrice']].tail(20).copy()

#differenze
ultimi_20['Differenze'] = ultimi_20['DealerPrice'] - ultimi_20['StandardCost']
ultimi_20['Markup_%'] = (ultimi_20['Differenze'] / ultimi_20['StandardCost']) * 100

print(ultimi_20)

---
--- Qual è il prezzo medio per i prodotti di colore blu? ---
La media dei prezzi dei prodotti blue è: 516.06
---
--- Qual è il prezzo medio per i prodotti di colore rosso o nero?  ---
La media dei prezzi dei prodotti rosi e neri è: 550.25
---
--- Qual è il prezzo massimo per i prodotti di taglia 42 e peso oltre i 10 Kg?  ---
Prezzo massimo (Taglia 42, Peso > 10): 2039.99
---
--- Qual è il nome inglese e il costo di produzione (StandardCost) di tutti i prodotti di taglia 42, peso oltre i 10 Kg e colore argento?  ---
            EnglishProductName StandardCost
344    Mountain-100 Silver, 42    1912.1500
353    Mountain-200 Silver, 42    1117.8600
354    Mountain-200 Silver, 42    1265.6200
588  Mountain-400-W Silver, 42     419.7800
591    Mountain-500 Silver, 42     308.2200
---
--- Visualizziamo lo StandardCost e il DealerPrice degli ultimi 20 elementi del dataset: quali sono le differenze? C'è un pattern? C'è qualche elemento che non lo segue?  ---
    StandardCost DealerPrice Differenze                        Markup_%
586     419.7800    461.6940    41.9140   9.984753918719329172423650484
587     419.7800    461.6940    41.9140   9.984753918719329172423650484
588     419.7800    461.6940    41.9140   9.984753918719329172423650484
589     419.7800    461.6940    41.9140   9.984753918719329172423650484
590     308.2200    338.9940    30.7740   9.984426708195444812147167608
591     308.2200    338.9940    30.7740   9.984426708195444812147167608
592     308.2200    338.9940    30.7740   9.984426708195444812147167608
593     308.2200    338.9940    30.7740   9.984426708195444812147167608
594     308.2200    338.9940    30.7740   9.984426708195444812147167608
595     294.5800    323.9940    29.4140   9.985063480209111277072442121
596     294.5800    323.9940    29.4140   9.985063480209111277072442121
597     294.5800    323.9940    29.4140   9.985063480209111277072442121
598     294.5800    323.9940    29.4140   9.985063480209111277072442121
599     294.5800    323.9940    29.4140   9.985063480209111277072442121
600      23.9700     32.3940     8.4240   35.14392991239048811013767209
601      44.9500     60.7440    15.7940   35.13681868743047830923248053
602      53.9400     72.8940    18.9540   35.13904338153503893214682981
603     343.6500    323.9940   -19.6560  -5.719773024879965080750763859
604     343.6500    323.9940   -19.6560  -5.719773024879965080750763859
605     343.6500    323.9940   -19.6560  -5.719773024879965080750763859

In [4]:
connection.close()

In [8]:
#Esercizio 1/2 Dai dataset in piattaforma, carichiamo il file con i dati dei pub, circoli e locali in Italia, chiamato Mappa-dei-pub-circoli-locali-in-Italia.csv 
#Nota: il dataset non ha un encoding UTF-8 ma Latin1; inoltre il separatore non è una virgola, ma un punto e virgola. 
#Dunque per leggerlo dovremo aggiungere i parametri encoding= e sep=, ad esempio: pd.read_csv(file_path, encoding="latin1", sep=";") 
#dove file_path è la posizione del file nel nostro calcolatore.

df_pub = pd.read_csv('Mappa-dei-pub-circoli-locali-in-Italia.csv', encoding="latin1", sep=";")
#display(df_pub)

#Esercizio 2/2 Esaminiamo il dataset: 
    #• quante attività ci sono nel quadrato di longitudine 9-10 e latitudine 45-46? 
    #• quante attività ci sono nella provincia di Vicenza? 
    #• quante attività ci sono in Lazio e Abruzzo assieme?


print("Valori nulli prima della pulizia:")
print(df_pub.isnull().sum())
# --- Data Cleaning ---
df_pub_pulito = df_pub.dropna(subset=['Longitudine', 'Latitudine', 'Provincia', 'Regione']).copy()
df_pub_pulito['Nome'] = df_pub_pulito['Nome'].fillna('Sconosciuto')
df_pub_pulito['Anno inserimento'] = df_pub_pulito['Anno inserimento'].fillna('Non specificato')
print("\n--- Diagnostica dataset pulito ---")
print("Valori nulli dopo la pulizia:")
print(df_pub_pulito.isnull().sum())

print('--- quante attività ci sono nel quadrato di longitudine 9-10 e latitudine 45-46? ---')
cond_longitudine = (df_pub_pulito['Longitudine'] >= 9) & (df_pub_pulito['Longitudine'] <= 10)
cond_latitudine = (df_pub_pulito['Latitudine'] >= 45) & (df_pub_pulito['Latitudine'] <= 46)
attività = df_pub_pulito[cond_longitudine & cond_latitudine]
print(f"Attività nel quadrato (Lon 9-10, Lat 45-46): {len(attività)}")

print("---")
print('--- quante attività ci sono nella provincia di Vicenza?  ---')
prov_vicenza = df_pub_pulito[df_pub_pulito['Provincia'] == 'VICENZA']
print(len(prov_vicenza))

print("---")
print('--- quante attività ci sono in Lazio e Abruzzo assieme?  ---')
reg_lazio_Abruzzo = df_pub_pulito[df_pub_pulito['Regione'].isin(['Lazio','Abruzzo'])]
print(len(reg_lazio_Abruzzo))

Valori nulli prima della pulizia:
Comune                               0
Provincia                            0
Regione                              0
Nome                               298
Anno inserimento                     0
Data e ora inserimento               0
Identificatore in OpenStreetMap      0
Longitudine                          0
Latitudine                           0
dtype: int64

--- Diagnostica dataset pulito ---
Valori nulli dopo la pulizia:
Comune                             0
Provincia                          0
Regione                            0
Nome                               0
Anno inserimento                   0
Data e ora inserimento             0
Identificatore in OpenStreetMap    0
Longitudine                        0
Latitudine                         0
dtype: int64
--- quante attività ci sono nel quadrato di longitudine 9-10 e latitudine 45-46? ---
Attività nel quadrato (Lon 9-10, Lat 45-46): 306
---
--- quante attività ci sono nella provincia di Vicenza?  ---
73
---
--- quante attività ci sono in Lazio e Abruzzo assieme?  ---
337

In [32]:
#Esercizio Il dataset insurance.csv dei beginner_datasets contiene dati su caratteristiche e abitudini delle persone rispetto ai costi individuali per le cure mediche come premio per le assicurazioni sulla salute. 
    #• Visualizziamone le dimensioni, un'anteprima, e osserviamo i nomi di colonna; 
    #• Quali sono le medie di charges rispetto a region? Ci sono differenze significative?
    #• E rispetto a smoker? E a sex? 
    #• Quali sono i descrittori statistici di bmi? Quali sono minimo, media e massimo di charges rispetto ai diversi quartili dei valori di bmi? 
#Nota: è lo stesso esercizio della volta scorsa, ma stavolta da eseguire con il metodo .groupby()

df_insurance = pd.read_csv('insurance.csv')
#display(df_insurance)

print('--- Visualizziamone le dimensioni, un\'anteprima, e osserviamo i nomi di colonna; ---')
print("--- Dimensioni del dataset ---")
print(df_insurance.shape)
print("\n--- Nomi delle colonne ---")
print(list(df_insurance.columns))
print("\n--- Anteprima del dataset ---")
print(df_insurance.head(5))


print('\n--- Quali sono le medie di charges rispetto a region? Ci sono differenze significative? ---')
media_charges_region = df_insurance.groupby('region')['charges'].mean().round(2)
print(media_charges_region)

print('\n--- E rispetto a smoker? E a sex? ---')
media_charges_smoker = df_insurance.groupby('smoker')['charges'].mean().round(2)
media_charges_sex = df_insurance.groupby('sex')['charges'].mean().round(2)
print('Smoker :',media_charges_smoker)
print('\nSex:',media_charges_sex)

print('\n--- Quali sono i descrittori statistici di bmi? Quali sono minimo, media e massimo di charges rispetto ai diversi quartili dei valori di bmi?  ---')
print(df_insurance['bmi'].describe().round(2))
bmi_quartile = pd.qcut(df_insurance['bmi'], q=4, precision=2) #qcut divide i valori in 4 quartili
charges_by_bmi_quartile = df_insurance.groupby(bmi_quartile, observed=True)['charges'].agg(['min', 'mean', 'max']).round(2)
print(charges_by_bmi_quartile)

--- Visualizziamone le dimensioni, un'anteprima, e osserviamo i nomi di colonna; ---
--- Dimensioni del dataset ---
(1338, 7)

--- Nomi delle colonne ---
['age', 'sex', 'bmi', 'children', 'smoker', 'region', 'charges']

--- Anteprima del dataset ---
   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

--- Quali sono le medie di charges rispetto a region? Ci sono differenze significative? ---
region
northeast    13406.38
northwest    12417.58
southeast    14735.41
southwest    12346.94
Name: charges, dtype: float64

--- E rispetto a smoker? E a sex? ---
Smoker : smoker
no      8434.27
yes    32050.23
Name: charges, dtype: float64

Sex: sex
female    12569.58
male      13956.75
Name: charges, dtype: float64

--- Quali sono i descrittori statistici di bmi? Quali sono minimo, media e massimo di charges rispetto ai diversi quartili dei valori di bmi?  ---
count    1338.00
mean       30.66
std         6.10
min        15.96
25%        26.30
50%        30.40
75%        34.69
max        53.13
Name: bmi, dtype: float64
                                min      mean       max
bmi
(15.950000000000001, 26.3]  1121.87  10360.66  38245.59
(26.3, 30.4]                1131.51  11407.83  62592.87
(30.4, 34.69]               1135.94  14358.17  60021.40
(34.69, 53.13]              1141.45  16987.94  63770.43

In [52]:
#Esercizio Carichiamo in un DataFrame il dataset iris.csv dei beginner_datasets e calcoliamo: 
    #• La media della lunghezza dei petali di tutto il dataset 
    #• La media della lunghezza dei petali per ogni specie di Iris, utilizzando il metodo .groupby() 
    #• Media, minimo e massimo della larghezza dei sepali per ogni specie, utilizzando .groupby() e .agg()

df_iris = pd.read_csv('iris.csv')
#DataCleaning
#display(df_iris.info)
df_iris.drop_duplicates(inplace=True) #3 duplicati tolti
display(df_iris.info)

print('--- La media della lunghezza dei petali di tutto il dataset ---')
media_petali = df_iris['petal_length'].mean().round(2)
print(media_petali)

print('\n--- La media della lunghezza dei petali per ogni specie di Iris, utilizzando il metodo .groupby() ---')
media_petali_per_species = df_iris.groupby('species')['petal_length'].mean().round(2)
print(media_petali_per_species)

print('\n--- Media, minimo e massimo della larghezza dei sepali per ogni specie, utilizzando .groupby() e .agg() ---')
stats_sepali = df_iris.groupby('species')['sepal_width'].agg(['mean', 'min', 'max']).round(2)
print('La media della larghezza dei Sepali è:\n',stats_sepali)

<bound method DataFrame.info of      sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[147 rows x 5 columns]>

--- La media della lunghezza dei petali di tutto il dataset ---
3.78

--- La media della lunghezza dei petali per ogni specie di Iris, utilizzando il metodo .groupby() ---
species
Iris-setosa        1.46
Iris-versicolor    4.26
Iris-virginica     5.56
Name: petal_length, dtype: float64

--- Media, minimo e massimo della larghezza dei sepali per ogni specie, utilizzando .groupby() e .agg() ---
La media della larghezza dei Sepali è:
                  mean  min  max
species
Iris-setosa      3.43  2.3  4.4
Iris-versicolor  2.77  2.0  3.4
Iris-virginica   2.98  2.2  3.8

In [72]:
#Esercizio Nei beginner_datasets, il dataset wine.csv contiene delle analisi organolettiche su diverse qualità di vini: 
    #• Qual è la media di concentrazione alcolica per ogni qualità? Ci sono differenze? E rispetto alla media totale? 
    #• C'è differenza nella concentrazione alcolica per vini bianchi e vini rossi? 
    #• Rifacendo le analisi dei due punti precedenti ma per il pH, cambia qualcosa? 
    #• E per i solfati?

df_wine = pd.read_csv('wine.csv')
#DataCleaning
df_wine_cleaned = df_wine.drop_duplicates()
df_w = df_wine_cleaned

display(df_w)
print('--- Qual è la media di concentrazione alcolica per ogni qualità? Ci sono differenze? E rispetto alla media totale? ---')
media_concentrazione_qualita = df_w.groupby('quality')['alcohol'].mean().round(2)
media_totale = df_w['alcohol'].mean().round(2)
print("La media di concentrazione alcolica per ogni qualità è:\n",media_concentrazione_qualita,"\nTendenza generale è al rialzo: i vini di qualità superiore tendono ad avere concentrazioni alcoliche più elevate.")
print("La media di concentrazione alcolica totale è:\n",media_totale,"\nI vini di qualità inferiore (punteggi 3–5) scendono al di sotto di questa media generale, mentre i vini di qualità superiore (punteggi 6–9) si collocano al di sopra.")

print('--- C\'è differenza nella concentrazione alcolica per vini bianchi e vini rossi? ---')
media_concentrazione_vini = df_w.groupby('type')['alcohol'].mean().round(2)
display(media_concentrazione_vini)

print('--- Rifacendo le analisi dei due punti precedenti ma per il pH, cambia qualcosa? ---')
media_concentrazione_qualita_ph = df_w.groupby('quality')['pH'].mean().round(2)
media_totale_ph = df_w['pH'].mean().round(2)
media_concentrazione_vini_ph = df_w.groupby('type')['pH'].mean().round(2)
print("La media di concentrazione del ph per ogni qualità è:\n",media_concentrazione_qualita_ph,"Non ci sono particolari differenze")
print("La media di concentrazione alcolica totale è\n:",media_totale_ph,"Nessuna particolare differenza con il totale")
display(media_concentrazione_vini_ph,"Nessuna differenza tra vino bianco e rosso")

print('\n--- E per i solfati? ---')
media_concentrazione_qualita_solfati = df_w.groupby('quality')['sulphates'].mean().round(2)
media_totale_solfati = df_w['sulphates'].mean().round(2)
media_concentrazione_vini_solfati = df_w.groupby('type')['sulphates'].mean().round(2)
print("La media di concentrazione dei solfati per ogni qualità è:\n", media_concentrazione_qualita_solfati)
print("\nLa media di concentrazione dei solfati totale è:\n", media_totale_solfati)
display(media_concentrazione_vini_solfati)
print("C'è una differenza significativa: i vini rossi contengono livelli di solfati notevolmente più alti rispetto ai vini bianchi.")

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,type
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,red
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5,red
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5,red
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6,red
5,7.4,0.66,0.00,1.8,0.075,13.0,40.0,0.99780,3.51,0.56,9.4,5,red
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6492,6.2,0.21,0.29,1.6,0.039,24.0,92.0,0.99114,3.27,0.50,11.2,6,white
6493,6.6,0.32,0.36,8.0,0.047,57.0,168.0,0.99490,3.15,0.46,9.6,5,white
6494,6.5,0.24,0.19,1.2,0.041,30.0,111.0,0.99254,2.99,0.46,9.4,6,white
6495,5.5,0.29,0.30,1.1,0.022,20.0,110.0,0.98869,3.34,0.38,12.8,7,white
6496,6.0,0.21,0.38,0.8,0.020,22.0,98.0,0.98941,3.26,0.32,11.8,6,white

--- Qual è la media di concentrazione alcolica per ogni qualità? Ci sono differenze? E rispetto alla media totale? ---
La media di concentrazione alcolica per ogni qualità è:
 quality
3    10.22
4    10.22
5     9.87
6    10.65
7    11.51
8    11.91
9    12.18
Name: alcohol, dtype: float64
Tendenza generale è al rialzo: i vini di qualità superiore tendono ad avere concentrazioni alcoliche più elevate.
La media di concentrazione alcolica totale è:
 10.55
I vini di qualità inferiore (punteggi 3–5) scendono al di sotto di questa media generale, mentre i vini di qualità superiore (punteggi 6–9) si collocano al di sopra.
--- C'è differenza nella concentrazione alcolica per vini bianchi e vini rossi? ---

type
red      10.43
white    10.59
Name: alcohol, dtype: float64

--- Rifacendo le analisi dei due punti precedenti ma per il pH, cambia qualcosa? ---
La media di concentrazione del ph per ogni qualità è:
 quality
3    3.26
4    3.24
5    3.21
6    3.22
7    3.24
8    3.24
9    3.31
Name: pH, dtype: float64 Non ci sono particolari differenze
La media di concentrazione alcolica totale è
: 3.22 Nessuna particolare differenza con il totale

type
red      3.31
white    3.20
Name: pH, dtype: float64

'Nessuna differenza tra vino bianco e rosso'

--- E per i solfati? ---
La media di concentrazione dei solfati per ogni qualità è:
 quality
3    0.51
4    0.51
5    0.53
6    0.53
7    0.55
8    0.52
9    0.47
Name: sulphates, dtype: float64

La media di concentrazione dei solfati totale è:
 0.53

type
red      0.66
white    0.49
Name: sulphates, dtype: float64

C'è una differenza significativa: i vini rossi contengono livelli di solfati notevolmente più alti rispetto ai vini bianchi.

In [87]:
#Esercizio 1/3 Nei beginner_datasets, il file boston.csv contiene il Boston Housing Dataset, 
#che deriva dalle informazioni raccolte dal Census Service degli Stati Uniti sulle abitazioni nell'area di Boston. 
 #Di seguito vengono descritte le colonne del dataset: 
    #• CRIM - tasso di criminalità pro capite per città 
    #• ZN - proporzione di terreni residenziali suddivisi in zone per lotti superiori a 25.000 piedi quadrati. 
    #• INDUS - percentuale di acri di attività commerciali non al dettaglio per città. 
    #• CHAS - variabile dummy del fiume Charles (1 se il tratto costeggia il fiume; 0 altrimenti)
#Esercizio 2/3 
    #• NOX - concentrazione di ossidi di azoto (parti per 10 milioni). 
    #• RM - numero medio di stanze per abitazione 
    #• AGE - proporzione di unità abitative occupate da proprietari costruite prima del 1940 
    #• DIS - distanze ponderate da cinque centri occupazionali di Boston 
    #• RAD - indice di accessibilità alle autostrade radiali 
    #• TAX - aliquota dell'imposta fondiaria sul valore pieno per 10.000 dollari 
    #• PTRATIO - rapporto alunni-insegnanti per città 
    #• BLACK - la percentuale di neri per città 
    #• LSTAT - % di popolazione di condizione più bassa 11 
    #• MEDV - Valore mediano delle case, espresso in migliaia di dollari
#Esercizio 3/3 
    #• La media del prezzo delle case cambia a seconda della distanza dal fiume Charles? 
    #• Si nota una correlazione tra il tasso di criminalità e il valore delle abitazioni? Come si può spiegare il risultato? 
    #• Qual è la media del numero di stanze rispetto al rapporto alunni-insegnanti? E del valore delle case? Appare esserci una qualche correlazione? Come si può spiegare il risultato? 
    #• Rispetto all'accessibilità alle autostrade, cambia qualcosa la media delle età delle abitazioni? E del numero di stanze? E delle tasse?

df_b = pd.read_csv('boston.csv')
#Data cleaning
#eliminiamo i duplicati
df_b.drop_duplicates(inplace=True)
df_b.info()

print('--- La media del prezzo delle case cambia a seconda della distanza dal fiume Charles? ---')
media_medv_by_chas = df_b.groupby('chas')['medv'].mean()
print(media_medv_by_chas, "\nLe case vicino al fiume Charles hanno un valore medio nettamente superiore")

print('\n--- Si nota una correlazione tra il tasso di criminalità e il valore delle abitazioni? Come si può spiegare il risultato? ---')
corr_crim_medv = df_b['crim'].corr(df_b['medv'])
print("Crime-Value Correlation:", corr_crim_medv, "è una correlazione negativa: all'aumentare della criminalità, il valore delle abitazioni scende.")

print('\n--- Qual è la media del numero di stanze rispetto al rapporto alunni-insegnanti? E del valore delle case? Appare esserci una qualche correlazione? Come si può spiegare il risultato? ---')
corr_ptratio_rm = df_b['ptratio'].corr(df_b['rm'])
corr_ptratio_medv = df_b['ptratio'].corr(df_b['medv'])
print("PTRATIO-Rooms Correlation:", corr_ptratio_rm)
print("PTRATIO-Value Correlation:", corr_ptratio_medv)
print("Sono correlazioni negative: le zone con scuole più affollate (alto PTRATIO) presentano case più piccole e di minor valore.")

print('\n--- Rispetto all\'accessibilità alle autostrade, cambia qualcosa la media delle età delle abitazioni? E del numero di stanze? E delle tasse? ---')
avg_metrics_by_rad = df_b.groupby('rad')[['age', 'rm', 'tax']].mean()
print(avg_metrics_by_rad, "\nDifferenza netta per RAD=24: qui le case sono molto più vecchie e subiscono la tassazione massima.")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   crim     506 non-null    float64
 1   zn       506 non-null    float64
 2   indus    506 non-null    float64
 3   chas     506 non-null    int64
 4   nox      506 non-null    float64
 5   rm       506 non-null    float64
 6   age      506 non-null    float64
 7   dis      506 non-null    float64
 8   rad      506 non-null    int64
 9   tax      506 non-null    int64
 10  ptratio  506 non-null    float64
 11  black    506 non-null    float64
 12  lstat    506 non-null    float64
 13  medv     506 non-null    float64
dtypes: float64(11), int64(3)
memory usage: 55.5 KB
--- La media del prezzo delle case cambia a seconda della distanza dal fiume Charles? ---
chas
0    22.093843
1    28.440000
Name: medv, dtype: float64
Le case vicino al fiume Charles hanno un valore medio nettamente superiore

--- Si nota una correlazione tra il tasso di criminalità e il valore delle abitazioni? Come si può spiegare il risultato? ---
Crime-Value Correlation: -0.3883046085868114 è una correlazione negativa: all'aumentare della criminalità, il valore delle abitazioni scende.

--- Qual è la media del numero di stanze rispetto al rapporto alunni-insegnanti? E del valore delle case? Appare esserci una qualche correlazione? Come si può spiegare il risultato? ---
PTRATIO-Rooms Correlation: -0.3555014945590855
PTRATIO-Value Correlation: -0.5077866855375615
Sono correlazioni negative: le zone con scuole più affollate (alto PTRATIO) presentano case più piccole e di minor valore.

--- Rispetto all'accessibilità alle autostrade, cambia qualcosa la media delle età delle abitazioni? E del numero di stanze? E delle tasse? ---
           age        rm         tax
rad
1    45.025000  6.555850  291.450000
2    64.770833  6.649958  260.666667
3    49.310526  6.473026  246.078947
4    60.841818  6.133118  335.981818
5    69.223478  6.393157  331.843478
6    60.142308  6.104731  372.884615
7    40.141176  6.647765  304.411765
8    67.350000  6.950792  301.250000
24   89.805303  6.022152  666.000000
Differenza netta per RAD=24: qui le case sono molto più vecchie e subiscono la tassazione massima.

In [97]:
#Esercizio 1/3 Abbiamo un DataFrame di dipendenti: 
employees_df = pd.DataFrame({ 'employee_id': [101, 102, 103, 104, 105], 
                              'name': ['Alice', 'Bob', 'Charlie', 'David', 'Emma'], 
                              'department_id': [1, 2, 1, 2, 3] })

#Esercizio 2/3 E un DataFrame di dipartimenti: 
departments_df = pd.DataFrame({ 'department_id': [1, 2, 3], 
                                'department_name': ['HR', 'IT', 'Finance'], 
                                'location': ['New York', 'San Francisco', 'Chicago'] })

#Esercizio 3/3 Unire questi DataFrame in base alla colonna comune department_id, in modo da avere nel risultato informazioni sia sui dipendenti che sui dipartimenti, usando la funzione .merge() 
    #• Per ogni DataFrame, trasformare la colonna department_id nell'indice, facendo in modo che la modifica sia permanente; poi unire i due dataset mediante il metodo .join() 
    #• Ci sono differenze nel risultato? Quali? Perché?
display(employees_df)
display(departments_df)

merged_df = pd.merge(employees_df, departments_df, on='department_id')

print("Risultato con .merge():")
display(merged_df)

employees_df.set_index('department_id', inplace=True)
departments_df.set_index('department_id', inplace=True)

joined_df = employees_df.join(departments_df)

print("\nRisultato con .join():")
display(joined_df)

print("\nLe differenze sono visive e strutturali, \nNel DataFrame merged_df (creato con .merge()), la colonna department_id appare come una normale colonna del dataset e l\'indice della tabella è quello posizionale di default (0, 1, 2, 3, 4).")
print("\nNel DataFrame joined_df (creato con .join()), department_id non è più una colonna standard, ma è diventato l\'indice di riga (evidenziato visivamente spostato a sinistra o su un livello diverso quando stampato a schermo).")

   employee_id     name  department_id
0          101    Alice              1
1          102      Bob              2
2          103  Charlie              1
3          104    David              2
4          105     Emma              3

   department_id department_name       location
0              1              HR       New York
1              2              IT  San Francisco
2              3         Finance        Chicago

Risultato con .merge():

   employee_id     name  department_id department_name       location
0          101    Alice              1              HR       New York
1          102      Bob              2              IT  San Francisco
2          103  Charlie              1              HR       New York
3          104    David              2              IT  San Francisco
4          105     Emma              3         Finance        Chicago

Risultato con .join():

               employee_id     name department_name       location
department_id
1                      101    Alice              HR       New York
2                      102      Bob              IT  San Francisco
1                      103  Charlie              HR       New York
2                      104    David              IT  San Francisco
3                      105     Emma         Finance        Chicago

Le differenze sono visive e strutturali,
Nel DataFrame merged_df (creato con .merge()), la colonna department_id appare come una normale colonna del dataset e l'indice della tabella è quello posizionale di default (0, 1, 2, 3, 4).

Nel DataFrame joined_df (creato con .join()), department_id non è più una colonna standard, ma è diventato l'indice di riga (evidenziato visivamente spostato a sinistra o su un livello diverso quando stampato a schermo).

In [100]:
#Esercizio 
    #• Dal database AdventureWorksDW importiamo le tabelle dimemployee e dimemployeesalesterritory come DataFrame 
    #• Effettuiamo un join tra i due DataFrame usando le colonne EmployeeKey 
    #• Controlliamo la dimensione del DataFrame risultante: è quella attesa? 
    #• Importiamo ora la tabella dimsalesterritory ed effettuiamo un join tra questa e il DataFrame risultante della join precedente, usando le colonne SalesTerritoryKey • Su questo DataFrame contare quanti dipendenti ci sono per ogni paese (country) e per ogni regione (region) 
    #• Valutiamo la media del BaseRate per ogni paese: ci sono differenze?

dotenv.load_dotenv(dotenv_path=".env", override=True)
username = os.getenv("username")
password = os.getenv("password")
hostname = os.getenv("hostname")
database = os.getenv("database")

connection = pymysql.connect(
    host=hostname,
    user=username,
    password=password,
    database=database,
    cursorclass=pymysql.cursors.DictCursor,
)
cursor = connection.cursor()

query_employee = "SELECT * FROM dimemployee;"
query_territory = "SELECT * FROM dimemployeesalesterritory;"

cursor.execute(query_employee)
result_employee = cursor.fetchall()
df_employee = pd.DataFrame(result_employee)

cursor.execute(query_territory)
result_territory = cursor.fetchall()
df_territory = pd.DataFrame(result_territory)

display(df_employee)
display(df_territory)

mergeAdw = pd.merge(df_employee, df_territory, on='EmployeeKey')
display(mergeAdw.shape)

query_sales_territory = "SELECT * FROM dimsalesterritory;"
cursor.execute(query_sales_territory)
result_sales_territory = cursor.fetchall()
df_sales_territory = pd.DataFrame(result_sales_territory)

cursor.close()
connection.close()

final_mergeAdw = pd.merge(mergeAdw, df_sales_territory, on='SalesTerritoryKey')

employee_count = final_mergeAdw.groupby(['SalesTerritoryCountry', 'SalesTerritoryRegion'])['EmployeeKey'].count().reset_index(name='EmployeeCount')

display(employee_count)

avg_baserate = final_mergeAdw.groupby('SalesTerritoryCountry')['BaseRate'].mean().reset_index(name='AverageBaseRate')

display(avg_baserate)

,EmployeeKey,ParentEmployeeKey,EmployeeNationalIDAlternateKey,ParentEmployeeNationalIDAlternateKey,FirstName,LastName,MiddleName,NameStyle,Title,HireDate,BirthDate,LoginID,EmailAddress,Phone,MaritalStatus,EmergencyContactName,EmergencyContactPhone,SalariedFlag,Gender,PayFrequency,BaseRate,VacationHours,SickLeaveHours,CurrentFlag,SalesPersonFlag,DepartmentName,EmployeePhoto,Position
0,1,18.0,14417807,446466105.0,Guy,Gilbert,R,0,Production Technician - WC60,2006-01-28,1981-11-12,AW\guy-gilbert,guy-gilbert@adventureworks.com,320-555-0195,M,Guy Gilbert,320-555-0195,0,M,1,12.4500,21,30,1,0,Production,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,None
1,2,7.0,253022876,24756624.0,Kevin,Brown,F,0,Marketing Assistant,2006-08-26,1986-12-01,AW\kevin-brown,kevin-brown@adventureworks.com,150-555-0189,S,Kevin Brown,150-555-0189,0,M,2,13.4615,42,41,1,0,Marketing,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,None
2,3,14.0,509647174,245797967.0,Roberto,Tamburello,None,0,Engineering Manager,2007-06-11,1974-06-12,AW\roberto-tamburello,roberto-tamburello@adventureworks.com,212-555-0187,M,Roberto Tamburello,212-555-0187,1,M,2,43.2692,2,21,1,0,Engineering,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,None
3,4,3.0,112457891,509647174.0,Rob,Walters,None,0,Senior Tool Designer,2007-07-05,1974-07-23,AW\rob-walters,rob-walters@adventureworks.com,612-555-0100,S,Rob Walters,612-555-0100,0,M,2,29.8462,48,80,1,0,Tool Design,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,None
4,5,3.0,112457891,509647174.0,Rob,Walters,None,0,Senior Tool Designer,2007-07-05,1974-07-23,AW\rob-walters,rob-walters@adventureworks.com,612-555-0100,S,Rob Walters,612-555-0100,0,M,2,29.8462,48,80,1,0,Tool Design,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
291,292,290.0,134219713,982310417.0,Ranjit,Varkey Chudukatil,R,0,Sales Representative,2011-12-29,1975-04-30,AW\ranjit-varkey-chudukatil,ranjit-varkey-chudukatil@adventureworks.com,1 (11) 500 555-0117,S,Ranjit Varkey Chudukatil,1 (11) 500 555-0117,1,M,2,23.0769,34,37,1,1,Sales,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,Sales Representative
292,293,272.0,90836195,502097814.0,Tete,Mensa-Annan,A,0,Sales Representative,2012-04-30,1977-08-05,AW\tete-mensa-annan,tete-mensa-annan@adventureworks.com,615-555-0153,M,Tete Mensa-Annan,615-555-0153,1,M,2,23.0769,39,39,1,1,Sales,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,Sales Representative
293,294,277.0,481044938,112432117.0,Syed,Abbas,E,0,Pacific Sales Manager,2012-10-12,1974-08-11,AW\syed-abbas,syed-abbas@adventureworks.com,926-555-0182,M,Syed Abbas,926-555-0182,1,M,2,48.1010,20,30,1,1,Sales,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,Sales Manager
294,295,290.0,954276278,982310417.0,Rachel,Valdez,B,0,Sales Representative,2012-12-28,1975-02-06,AW\rachel-valdez,rachel-valdez@adventureworks.com,1 (11) 500 555-0140,S,Rachel Valdez,1 (11) 500 555-0140,1,F,2,23.0769,35,37,1,1,Sales,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,Sales Representative
295,296,294.0,758596752,481044938.0,Lynn,Tsoflias,N,0,Sales Representative,2012-12-28,1970-10-16,AW\lynn-tsoflias,lynn-tsoflias@adventureworks.com,1 (11) 500 555-0190,S,Lynn Tsoflias,1 (11) 500 555-0190,1,F,2,23.0769,36,38,1,1,Sales,b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\...,Sales Representative

    EmployeeKey  SalesTerritoryKey
0           272                  1
1           277                  1
2           286                  1
3           289                  1
4           293                  1
5           272                  2
6           277                  2
7           281                  2
8           272                  3
9           277                  3
10          281                  3
11          282                  3
12          283                  3
13          272                  4
14          277                  4
15          282                  4
16          286                  4
17          287                  4
18          272                  5
19          277                  5
20          281                  5
21          285                  5
22          272                  6
23          277                  6
24          284                  6
25          288                  6
26          277                  7
27          290                  7
28          291                  7
29          292                  7
30          277                  8
31          290                  8
32          295                  8
33          277                  9
34          294                  9
35          296                  9
36          277                 10
37          290                 10
38          291                 10

(39, 29)

  SalesTerritoryCountry SalesTerritoryRegion  EmployeeCount
0             Australia            Australia              3
1                Canada               Canada              4
2                France               France              4
3               Germany              Germany              3
4        United Kingdom       United Kingdom              3
5         United States              Central              5
6         United States            Northeast              3
7         United States            Northwest              5
8         United States            Southeast              4
9         United States            Southwest              5

  SalesTerritoryCountry AverageBaseRate
0             Australia       47.764433
1                Canada        41.59255
2                France        41.59255
3               Germany       47.764433
4        United Kingdom       47.764433
5         United States       39.909309